SELECT WFAPPROVAL_STATUS,DOC_SEQUENCE_VALUE,
            INVOICE_NUM
FROM ap_invoices_all
WHERE WFAPPROVAL_STATUS = 'REQUIRED';

select *
from ap_suppliers
where segment1 = 102349;

SELECT DISTINCT  WFAPPROVAL_STATUS
FROM ap_invoices_all;



SELECT *
FROM HZ_LOCATIONS;

SELECT  tax_reference
FROM HZ_PARTY_SITES
WHERE PARTY_SITE_ID = 31505;

SELECT *
FROM HZ_PARTIES
WHERE PARTY_ID = 33100;

SELECT *
FROM HZ_CUST_ACCOUNTS_ALL
WHERE ACCOUNT_NUMBER = 1744;

select tax_reference
from hz_cust_site_uses_all
where cust_acct_site_id = 5601;

SELECT *
FROM HZ_CUST_ACCT_SITES_ALL
WHERE CUST_ACCT_SITE_ID = 5601;