select *
from ra_interface_lines_all;

select *
from ra_interface_lines_all
where interface_line_attribute1 = '3010005140';


  SELECT /* no hint */ COUNT(*) 
    from   ra_interface_lines_all l 
WHERE NVL(INTERFACE_STATUS, '~') != 'P'
AND (REQUEST_ID IS NULL
)
AND BATCH_SOURCE_NAME = 'Invoice-Parts'
AND DECODE(-99, -99, ORG_ID, -99) = ORG_ID 

AND SALES_ORDER = '3010005140' AND LINK_TO_LINE_ATTRIBUTE1 IS NULL
AND LINK_TO_LINE_ATTRIBUTE2 IS NULL
AND LINK_TO_LINE_ATTRIBUTE3 IS NULL
AND LINK_TO_LINE_ATTRIBUTE4 IS NULL
AND LINK_TO_LINE_ATTRIBUTE5 IS NULL
AND LINK_TO_LINE_ATTRIBUTE6 IS NULL
AND LINK_TO_LINE_ATTRIBUTE7 IS NULL
AND LINK_TO_LINE_ATTRIBUTE8 IS NULL
AND LINK_TO_LINE_ATTRIBUTE9 IS NULL
AND LINK_TO_LINE_ATTRIBUTE10 IS NULL
AND LINK_TO_LINE_ATTRIBUTE11 IS NULL
AND LINK_TO_LINE_ATTRIBUTE12 IS NULL
AND LINK_TO_LINE_ATTRIBUTE13 IS NULL
AND LINK_TO_LINE_ATTRIBUTE14 IS NULL
AND LINK_TO_LINE_ATTRIBUTE15 IS NULL;

select *
from ra_customer_trx_all
where interface_header_attribute1 = '3010005143';

SELECT *
FROM RA_CUSTOMER_TRX_ALL
WHERE INTERFACE_HEADER_ATTRIBUTE1 = '3010002044';

SELECT *
FROM RA_INTERFACE_LINES_ALL
WHERE INTERFACE_LINE_ATTRIBUTE1 = '3010011251';