SELECT  CID.ORGANIZATION_CODE
, HRO.NAME
, MMT.TRANSACTION_ID
, cid.organization_id
--, mck.segment1 as ITEM_CATEGORY_FAMILY
--, mck.segment2 as ITEM_CATEGORY_CLASS
--, MSI.ITEM_TYPE
--, FLV.MEANING as ITEM_TYPE_DESCRIPTION
--, MTY.TRANSACTION_TYPE_NAME
--, MMT.TRANSACTION_TYPE_ID
--, MSI.SEGMENT1 as item
--, MSI.DESCRIPTION
--, TRUNC(MMT.TRANSACTION_DATE) AS TRANSACTION_DATE
--, MMT.TRANSACTION_QUANTITY
--, MMT.TRANSACTION_UOM
--, MMT.TRANSACTION_SOURCE_NAME
--, CID.UNIT_COST
--, NVL(MMT.ACTUAL_COST,0) AS ACTUAL_COST
--, GCC.CONCATENATED_SEGMENTS   AS ACCOUNT_CODE_COMBINATION
--, GCC.SEGMENT6
--, CID.LINE_TYPE_NAME
--, CID.BASE_TRANSACTION_VALUE
, MAX(case
    when CID.BASE_TRANSACTION_VALUE > 0 then  CID.BASE_TRANSACTION_VALUE
    end) DEBIT
, MAX(case
    when CID.BASE_TRANSACTION_VALUE < 0 then  CID.BASE_TRANSACTION_VALUE
    end) CREDIT
--, cid.BASE_TRANSACTION_VALUE

FROM MTL_MATERIAL_TRANSACTIONS      MMT
,    MTL_SYSTEM_ITEMS_B             MSI
,    HR_ALL_ORGANIZATION_UNITS      HRO
,    MTL_TRANSACTION_TYPES          MTY
,    CST_INV_DISTRIBUTION_V         CID
,    GL_CODE_COMBINATIONS_KFV       GCC
,    FND_LOOKUP_VALUES_VL     FLV
,   MTL_ITEM_CATEGORIES  mtc
,  mtl_categories_kfv mck
WHERE 
--52146
msi.inventory_item_id = mtc.inventory_item_id and
MMT.ORGANIZATION_ID = mtc.ORGANIZATION_ID and
mtc.CATEGORY_ID =mck.CATEGORY_ID 
--and CID.ORGANIZATION_CODE in('DBS','IPS','NAC','RIO','IVP') 
 --MMT.TRANSACTION_TYPE_ID IN (32, 42, 100001, 100002)
--   AND MMT.transaction_type_id IN (10008)
--AND 
 --and 
 and  MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
AND   MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND   MMT.ORGANIZATION_ID = HRO.ORGANIZATION_ID
AND   MMT.TRANSACTION_TYPE_ID = MTY.TRANSACTION_TYPE_ID
--AND   TRUNC(MMT.TRANSACTION_DATE) BETWEEN :FROM_DATE AND :TO_DATE
AND   MMT.TRANSACTION_ID =  CID.TRANSACTION_ID
AND   MMT.ORGANIZATION_ID = CID.ORGANIZATION_ID
AND   CID.REFERENCE_ACCOUNT = GCC.CODE_COMBINATION_ID
AND FLV.LOOKUP_TYPE = 'ITEM_TYPE'
--AND  MTY.TRANSACTION_TYPE_NAME like 'Beg%'
--and MMT.TRANSACTION_DATE between '01-JAN-2017' and '31-JAN-2017'
and MSI.ITEM_TYPE = FLV.LOOKUP_CODE  
AND MCK.STRUCTURE_ID = '50388'
-- and gcc.segment6 = '65100'
    --  AND  mmt.transaction_id =274325
--AND TO_DATE(MMT.TRANSACTION_DATE) between '01-JAN-2017' and '15-JAN-2017'
group BY  CID.ORGANIZATION_CODE
, HRO.NAME
, MMT.TRANSACTION_ID
, cid.organization_id
ORDER BY MMT.TRANSACTION_ID;
-- having (select count(transaction_id) FROM mtl_material_transactions where transaction_id =       MMT.TRANSACTION_ID) > 3;--, BASE_TRANSACTION_VALUE DESC

