SELECT DISTINCT
IPSR.CALL_APP_PAY_SERVICE_REQ_CODE,
IDPA.PAYEE_PARTY_ID,
IDPA.DOCUMENT_PAYABLE_ID REF_NUM,
HP.PARTY_NAME PAYEE, 
IDPA.CALLING_APP_DOC_REF_NUMBER INVOICE_NUM,
IDPA.PAYMENT_CURRENCY_CODE,
IDPA.PAYMENT_AMOUNT,
IDPA.DOCUMENT_CURRENCY_CODE,
IDPA.DOCUMENT_AMOUNT,
TO_CHAR(IDPA.DOCUMENT_DATE, 'DD-MON-YYYY') INVOICE_DATE,
TO_CHAR(IDPA.PAYMENT_DATE, 'DD-MON-YYYY') PAYMENT_DATE,
IDPA.DOCUMENT_TYPE,
IDPA.DOCUMENT_STATUS PROCESSING_STATUS,
IDPA.DOCUMENT_SEQUENCE_VALUE VOUCHER_NUMBER,
(nvl(AIA.INVOICE_AMOUNT,0)-NVL(AIA.TOTAL_TAX_AMOUNT,0)) NET_AMOUNT,
AIA.TOTAL_TAX_AMOUNT VAT_AMOUNT,
AIA.INVOICE_AMOUNT,
(SELECT nvl(SUM(AMOUNT),0) FROM ap_invoice_lines_all
WHERE invoice_id = aila.invoice_id AND LINE_TYPE_LOOKUP_CODE = 'AWT')  WHT_AMOUNT
FROM IBY_DOCS_PAYABLE_ALL IDPA
LEFT JOIN IBY_PAY_SERVICE_REQUESTS IPSR
ON IDPA.PAYMENT_SERVICE_REQUEST_ID = IPSR.PAYMENT_SERVICE_REQUEST_ID
LEFT JOIN AP_INVOICES_ALL AIA
ON IDPA.CALLING_APP_DOC_UNIQUE_REF2 = AIA.INVOICE_ID
LEFT JOIN AP_INVOICE_LINES_ALL AILA
ON AIA.INVOICE_ID = AILA.INVOICE_ID
LEFT JOIN HZ_PARTIES HP
ON IDPA.PAYEE_PARTY_ID = HP.PARTY_ID
--WHERE IDPA.DOCUMENT_PAYABLE_ID IN (4088,4089)
WHERE IPSR.CALL_APP_PAY_SERVICE_REQ_CODE = :P_PAYMENT_PROCESS_REQ
AND LINE_TYPE_LOOKUP_CODE = 'ITEM'
order by IDPA.CALLING_APP_DOC_REF_NUMBER;


select IPSR.PAYMENT_SERVICE_REQUEST_ID,
         IPSR.CALL_APP_PAY_SERVICE_REQ_CODE,
         IPSR.PAYMENT_SERVICE_REQUEST_STATUS,
         IDPA.PAYMENT_DATE,
         CALLING_APP_DOC_REF_NUMBER,
         DOCUMENT_AMOUNT,
         CALLING_APP_DOC_UNIQUE_REF5,
         CALLING_APP_DOC_UNIQUE_REF4,
         CALLING_APP_DOC_UNIQUE_REF3,
         CALLING_APP_DOC_UNIQUE_REF2,
         CALLING_APP_DOC_UNIQUE_REF1,
         CALLING_APP_DOC_REF_NUMBER,
         IDPA.CALLING_APP_ID,
         
        -- IBPSR.CREATION_DATE
PAYMENT_AMOUNT
from IBY_DOCS_PAYABLE_ALL IDPA,
       IBY_PAY_SERVICE_REQUESTS IPSR
where 1 = 1
         AND  IDPA.PAYMENT_SERVICE_REQUEST_ID = IPSR.PAYMENT_SERVICE_REQUEST_ID
         AND IPSR.CALL_APP_PAY_SERVICE_REQ_CODE = 'GOOD HOUSE INDUSTRIES, INC-dec';
;

SELECT *
FROM iby_payments_all
WHERE PAYMENT_SERVICE_REQUEST_ID = 117;

SELECT *
FROM IBY_PAY_INSTRUCTIONS_ALL
WHERE PAYMENT_INSTRUCTION_ID = 10321;
WHERE PAY_ADMIN_ASSIGNED_REF_CODE LIKE '%40589%';



select pi.*
from IBY_PAY_INSTRUCTIONS_ALL pi
where pi.payment_instruction_id in
(SELECT payment_instruction_id
FROM iby_payments_all
WHERE payment_service_request_id in
(SELECT payment_service_request_id
FROM iby_pay_service_requests
WHERE calling_app_id = 200
AND call_app_pay_service_req_code = 'GOOD HOUSE INDUSTRIES, INC-dec')); 


select *
from IBY_PAY_SERVICE_REQUESTS;

select *
from IBY_PAY_INSTRUCTIONS_ALL;

